export const dummyDonors = [
  {
    fullName: "Asif Rahman",
    phone: "+8801710000031",
    email: "asif.rahman31@example.com",
    donorType: "blood",
    bloodGroup: "A+",
    lastDonated: "10 Nov 2023",
    district: "Mymensingh",
    upazilla: "Trishal",
    address: "House 31, Road 1",
    gender: "Male",
    birthDate: "15 Jan 1993",
    password: "Donor10###",
    donateStatus: true,
  },
  {
    fullName: "Maya Sultana",
    phone: "+8801710000032",
    email: "maya.sultana32@example.com",
    donorType: "blood",
    bloodGroup: "B+",
    lastDonated: "10 Nov 2023",
    district: "Mymensingh",
    upazilla: "Muktagacha",
    address: "House 32, Road 2",
    gender: "Female",
    birthDate: "20 Feb 1995",
    password: "Donor10###",
    donateStatus: true,
  },
  {
    fullName: "Kamrul Hasan",
    phone: "+8801710000033",
    email: "kamrul.hasan33@example.com",
    donorType: "blood",
    bloodGroup: "O-",
    lastDonated: "10 Nov 2023",
    district: "Mymensingh",
    upazilla: "Fulbaria",
    address: "House 33, Road 3",
    gender: "Male",
    birthDate: "25 Mar 1989",
    password: "Donor10###",
    donateStatus: true,
  },
  {
    fullName: "Tania Akter",
    phone: "+8801710000034",
    email: "tania.akter34@example.com",
    donorType: "blood",
    bloodGroup: "AB+",
    lastDonated: "10 Nov 2023",
    district: "Mymensingh",
    upazilla: "Bhaluka",
    address: "House 34, Road 4",
    gender: "Female",
    birthDate: "18 Apr 1994",
    password: "Donor10###",
    donateStatus: true,
  },
  {
    fullName: "Shakil Mahmud",
    phone: "+8801710000035",
    email: "shakil.mahmud35@example.com",
    donorType: "blood",
    bloodGroup: "A-",
    lastDonated: "10 Nov 2023",
    district: "Mymensingh",
    upazilla: "Nandail",
    address: "House 35, Road 5",
    gender: "Male",
    birthDate: "15 May 1992",
    password: "Donor10###",
    donateStatus: true,
  },
  {
    fullName: "Farhana Yasmin",
    phone: "+8801710000036",
    email: "farhana.yasmin36@example.com",
    donorType: "blood",
    bloodGroup: "B-",
    lastDonated: "10 Nov 2023",
    district: "Mymensingh",
    upazilla: "Gafargaon",
    address: "House 36, Road 6",
    gender: "Female",
    birthDate: "22 Jun 1996",
    password: "Donor10###",
    donateStatus: true,
  },
  {
    fullName: "Nazmul Haque",
    phone: "+8801710000037",
    email: "nazmul.haque37@example.com",
    donorType: "blood",
    bloodGroup: "O+",
    lastDonated: "10 Nov 2023",
    district: "Mymensingh",
    upazilla: "Ishwarganj",
    address: "House 37, Road 7",
    gender: "Male",
    birthDate: "11 Jul 1991",
    password: "Donor10###",
    donateStatus: true,
  },
  {
    fullName: "Rakhi Chowdhury",
    phone: "+8801710000038",
    email: "rakhi.chowdhury38@example.com",
    donorType: "blood",
    bloodGroup: "AB-",
    lastDonated: "10 Nov 2023",
    district: "Mymensingh",
    upazilla: "Haluaghat",
    address: "House 38, Road 8",
    gender: "Female",
    birthDate: "03 Aug 1997",
    password: "Donor10###",
    donateStatus: true,
  },
  {
    fullName: "Rubel Mia",
    phone: "+8801710000039",
    email: "rubel.mia39@example.com",
    donorType: "blood",
    bloodGroup: "A+",
    lastDonated: "10 Nov 2023",
    district: "Mymensingh",
    upazilla: "Dhobaura",
    address: "House 39, Road 9",
    gender: "Male",
    birthDate: "20 Sep 1987",
    password: "Donor10###",
    donateStatus: true,
  },
  {
    fullName: "Mithila Akter",
    phone: "+8801710000040",
    email: "mithila.akter40@example.com",
    donorType: "blood",
    bloodGroup: "B+",
    lastDonated: "10 Nov 2023",
    district: "Mymensingh",
    upazilla: "Phulpur",
    address: "House 40, Road 10",
    gender: "Female",
    birthDate: "01 Oct 1998",
    password: "Donor10###",
    donateStatus: true,
  },{
    fullName: "Jahangir Alam",
    phone: "+8801710000041",
    email: "jahangir.alam41@example.com",
    donorType: "blood",
    bloodGroup: "O+",
    lastDonated: "10 Nov 2023",
    district: "Mymensingh",
    upazilla: "Trishal",
    address: "House 41, Road 11",
    gender: "Male",
    birthDate: "10 Nov 1990",
    password: "Donor10###",
    donateStatus: true,
  },
  {
    fullName: "Sharmin Akter",
    phone: "+8801710000042",
    email: "sharmin.akter42@example.com",
    donorType: "blood",
    bloodGroup: "A+",
    lastDonated: "10 Nov 2023",
    district: "Mymensingh",
    upazilla: "Muktagacha",
    address: "House 42, Road 12",
    gender: "Female",
    birthDate: "02 Dec 1992",
    password: "Donor10###",
    donateStatus: true,
  },
  {
    fullName: "Hossain Ali",
    phone: "+8801710000043",
    email: "hossain.ali43@example.com",
    donorType: "blood",
    bloodGroup: "B-",
    lastDonated: "10 Nov 2023",
    district: "Mymensingh",
    upazilla: "Bhaluka",
    address: "House 43, Road 13",
    gender: "Male",
    birthDate: "15 Mar 1995",
    password: "Donor10###",
    donateStatus: true,
  },
  {
    fullName: "Jannatul Ferdous",
    phone: "+8801710000044",
    email: "jannatul.ferdous44@example.com",
    donorType: "blood",
    bloodGroup: "AB+",
    lastDonated: "10 Nov 2023",
    district: "Mymensingh",
    upazilla: "Ishwarganj",
    address: "House 44, Road 14",
    gender: "Female",
    birthDate: "28 Apr 1997",
    password: "Donor10###",
    donateStatus: true,
  },
  {
    fullName: "Salim Reza",
    phone: "+8801710000045",
    email: "salim.reza45@example.com",
    donorType: "blood",
    bloodGroup: "O-",
    lastDonated: "10 Nov 2023",
    district: "Mymensingh",
    upazilla: "Gafargaon",
    address: "House 45, Road 15",
    gender: "Male",
    birthDate: "17 Jul 1991",
    password: "Donor10###",
    donateStatus: true,
  },
  {
    fullName: "Nusrat Jahan",
    phone: "+8801710000046",
    email: "nusrat.jahan46@example.com",
    donorType: "blood",
    bloodGroup: "A-",
    lastDonated: "10 Nov 2023",
    district: "Mymensingh",
    upazilla: "Nandail",
    address: "House 46, Road 16",
    gender: "Female",
    birthDate: "10 Aug 1994",
    password: "Donor10###",
    donateStatus: true,
  },
  {
    fullName: "Mizanur Rahman",
    phone: "+8801710000047",
    email: "mizanur.rahman47@example.com",
    donorType: "blood",
    bloodGroup: "B+",
    lastDonated: "10 Nov 2023",
    district: "Mymensingh",
    upazilla: "Fulbaria",
    address: "House 47, Road 17",
    gender: "Male",
    birthDate: "22 Jun 1993",
    password: "Donor10###",
    donateStatus: true,
  },
  {
    fullName: "Rina Begum",
    phone: "+8801710000048",
    email: "rina.begum48@example.com",
    donorType: "blood",
    bloodGroup: "AB-",
    lastDonated: "10 Nov 2023",
    district: "Mymensingh",
    upazilla: "Phulpur",
    address: "House 48, Road 18",
    gender: "Female",
    birthDate: "12 Sep 1996",
    password: "Donor10###",
    donateStatus: true,
  },
  {
    fullName: "Alamgir Hossain",
    phone: "+8801710000049",
    email: "alamgir.hossain49@example.com",
    donorType: "blood",
    bloodGroup: "O+",
    lastDonated: "10 Nov 2023",
    district: "Mymensingh",
    upazilla: "Haluaghat",
    address: "House 49, Road 19",
    gender: "Male",
    birthDate: "20 Feb 1990",
    password: "Donor10###",
    donateStatus: true,
  },
  {
    fullName: "Tahmina Sultana",
    phone: "+8801710000050",
    email: "tahmina.sultana50@example.com",
    donorType: "blood",
    bloodGroup: "A+",
    lastDonated: "10 Nov 2023",
    district: "Mymensingh",
    upazilla: "Dhobaura",
    address: "House 50, Road 20",
    gender: "Female",
    birthDate: "30 Nov 1994",
    password: "Donor10###",
    donateStatus: true,
  },{
    fullName: "Shamim Hossain",
    phone: "+8801710000051",
    email: "shamim.hossain51@example.com",
    donorType: "blood",
    bloodGroup: "O+",
    lastDonated: "10 Nov 2023",
    district: "Mymensingh",
    upazilla: "Kishoreganj",
    address: "House 51, Road 21",
    gender: "Male",
    birthDate: "15 Mar 1995",
    password: "Donor10###",
    donateStatus: true,
  },
  {
    fullName: "Momena Begum",
    phone: "+8801710000052",
    email: "momena.begum52@example.com",
    donorType: "blood",
    bloodGroup: "A-",
    lastDonated: "10 Nov 2023",
    district: "Mymensingh",
    upazilla: "Bhaluka",
    address: "House 52, Road 22",
    gender: "Female",
    birthDate: "20 Jun 1992",
    password: "Donor10###",
    donateStatus: true,
  },
  {
    fullName: "Shah Alam",
    phone: "+8801710000053",
    email: "shah.alam53@example.com",
    donorType: "blood",
    bloodGroup: "B+",
    lastDonated: "10 Nov 2023",
    district: "Mymensingh",
    upazilla: "Trishal",
    address: "House 53, Road 23",
    gender: "Male",
    birthDate: "25 Jul 1994",
    password: "Donor10###",
    donateStatus: true,
  },
  {
    fullName: "Fahmida Sultana",
    phone: "+8801710000054",
    email: "fahmida.sultana54@example.com",
    donorType: "blood",
    bloodGroup: "AB+",
    lastDonated: "10 Nov 2023",
    district: "Mymensingh",
    upazilla: "Ishwarganj",
    address: "House 54, Road 24",
    gender: "Female",
    birthDate: "30 Oct 1993",
    password: "Donor10###",
    donateStatus: true,
  },
  {
    fullName: "Sabbir Rahman",
    phone: "+8801710000055",
    email: "sabbir.rahman55@example.com",
    donorType: "blood",
    bloodGroup: "O-",
    lastDonated: "10 Nov 2023",
    district: "Mymensingh",
    upazilla: "Muktagacha",
    address: "House 55, Road 25",
    gender: "Male",
    birthDate: "18 Dec 1991",
    password: "Donor10###",
    donateStatus: true,
  },
  {
    fullName: "Nasrin Akter",
    phone: "+8801710000056",
    email: "nasrin.akter56@example.com",
    donorType: "blood",
    bloodGroup: "A+",
    lastDonated: "10 Nov 2023",
    district: "Mymensingh",
    upazilla: "Fulbaria",
    address: "House 56, Road 26",
    gender: "Female",
    birthDate: "11 Sep 1990",
    password: "Donor10###",
    donateStatus: true,
  },
  {
    fullName: "Shuvo Dey",
    phone: "+8801710000057",
    email: "shuvo.dey57@example.com",
    donorType: "blood",
    bloodGroup: "B-",
    lastDonated: "10 Nov 2023",
    district: "Mymensingh",
    upazilla: "Nandail",
    address: "House 57, Road 27",
    gender: "Male",
    birthDate: "5 Apr 1992",
    password: "Donor10###",
    donateStatus: true,
  },
  {
    fullName: "Sultana Parvin",
    phone: "+8801710000058",
    email: "sultana.parvin58@example.com",
    donorType: "blood",
    bloodGroup: "O+",
    lastDonated: "10 Nov 2023",
    district: "Mymensingh",
    upazilla: "Gafargaon",
    address: "House 58, Road 28",
    gender: "Female",
    birthDate: "13 Mar 1994",
    password: "Donor10###",
    donateStatus: true,
  },
  {
    fullName: "Anwar Hossain",
    phone: "+8801710000059",
    email: "anwar.hossain59@example.com",
    donorType: "blood",
    bloodGroup: "A-",
    lastDonated: "10 Nov 2023",
    district: "Mymensingh",
    upazilla: "Haluaghat",
    address: "House 59, Road 29",
    gender: "Male",
    birthDate: "14 May 1993",
    password: "Donor10###",
    donateStatus: true,
  },
  {
    fullName: "Kausar Jahan",
    phone: "+8801710000060",
    email: "kausar.jahan60@example.com",
    donorType: "blood",
    bloodGroup: "AB-",
    lastDonated: "10 Nov 2023",
    district: "Mymensingh",
    upazilla: "Dhobaura",
    address: "House 60, Road 30",
    gender: "Female",
    birthDate: "22 Aug 1991",
    password: "Donor10###",
    donateStatus: true,
  },{
    fullName: "Irfan Ali",
    phone: "+8801710000061",
    email: "irfan.ali61@example.com",
    donorType: "blood",
    bloodGroup: "O+",
    lastDonated: "10 Nov 2023",
    district: "Mymensingh",
    upazilla: "Trishal",
    address: "House 61, Road 31",
    gender: "Male",
    birthDate: "12 Feb 1990",
    password: "Donor10###",
    donateStatus: true,
  },
  {
    fullName: "Rupa Akter",
    phone: "+8801710000062",
    email: "rupa.akter62@example.com",
    donorType: "blood",
    bloodGroup: "B+",
    lastDonated: "10 Nov 2023",
    district: "Mymensingh",
    upazilla: "Kishoreganj",
    address: "House 62, Road 32",
    gender: "Female",
    birthDate: "2 Apr 1995",
    password: "Donor10###",
    donateStatus: true,
  },
  {
    fullName: "Masud Rana",
    phone: "+8801710000063",
    email: "masud.rana63@example.com",
    donorType: "blood",
    bloodGroup: "A-",
    lastDonated: "10 Nov 2023",
    district: "Mymensingh",
    upazilla: "Nandail",
    address: "House 63, Road 33",
    gender: "Male",
    birthDate: "8 Jan 1992",
    password: "Donor10###",
    donateStatus: true,
  },
  {
    fullName: "Jannat Sultana",
    phone: "+8801710000064",
    email: "jannat.sultana64@example.com",
    donorType: "blood",
    bloodGroup: "AB+",
    lastDonated: "10 Nov 2023",
    district: "Mymensingh",
    upazilla: "Fulbaria",
    address: "House 64, Road 34",
    gender: "Female",
    birthDate: "30 Dec 1993",
    password: "Donor10###",
    donateStatus: true,
  },
  {
    fullName: "Habibur Rahman",
    phone: "+8801710000065",
    email: "habibur.rahman65@example.com",
    donorType: "blood",
    bloodGroup: "O-",
    lastDonated: "10 Nov 2023",
    district: "Mymensingh",
    upazilla: "Bhaluka",
    address: "House 65, Road 35",
    gender: "Male",
    birthDate: "4 May 1991",
    password: "Donor10###",
    donateStatus: true,
  },
  {
    fullName: "Shirin Akter",
    phone: "+8801710000066",
    email: "shirin.akter66@example.com",
    donorType: "blood",
    bloodGroup: "B-",
    lastDonated: "10 Nov 2023",
    district: "Mymensingh",
    upazilla: "Ishwarganj",
    address: "House 66, Road 36",
    gender: "Female",
    birthDate: "11 Nov 1990",
    password: "Donor10###",
    donateStatus: true,
  },
  {
    fullName: "Abul Hossain",
    phone: "+8801710000067",
    email: "abul.hossain67@example.com",
    donorType: "blood",
    bloodGroup: "A+",
    lastDonated: "10 Nov 2023",
    district: "Mymensingh",
    upazilla: "Muktagacha",
    address: "House 67, Road 37",
    gender: "Male",
    birthDate: "7 Aug 1994",
    password: "Donor10###",
    donateStatus: true,
  },
  {
    fullName: "Sohana Begum",
    phone: "+8801710000068",
    email: "sohana.begum68@example.com",
    donorType: "blood",
    bloodGroup: "O+",
    lastDonated: "10 Nov 2023",
    district: "Mymensingh",
    upazilla: "Gafargaon",
    address: "House 68, Road 38",
    gender: "Female",
    birthDate: "24 Jul 1992",
    password: "Donor10###",
    donateStatus: true,
  },
  {
    fullName: "Akash Das",
    phone: "+8801710000069",
    email: "akash.das69@example.com",
    donorType: "blood",
    bloodGroup: "AB-",
    lastDonated: "10 Nov 2023",
    district: "Mymensingh",
    upazilla: "Haluaghat",
    address: "House 69, Road 39",
    gender: "Male",
    birthDate: "15 Mar 1993",
    password: "Donor10###",
    donateStatus: true,
  },
  {
    fullName: "Shamima Khatun",
    phone: "+8801710000070",
    email: "shamima.khatun70@example.com",
    donorType: "blood",
    bloodGroup: "B+",
    lastDonated: "10 Nov 2023",
    district: "Mymensingh",
    upazilla: "Dhobaura",
    address: "House 70, Road 40",
    gender: "Female",
    birthDate: "18 Jun 1990",
    password: "Donor10###",
    donateStatus: true,
  },
  ];
  

  